### ISSUE TITLE
版本升级的问题

### ISSUE THREAD

**Issue by dayongchan** [wechat-group/weixin-java-tools-springmvc#1]
升级weixin-java-mp到2.0.3版本后很多报错的问题，原因是找不到2.0.3的包，请问这个版本的包上传到仓库了没有？

**Comment by binarywang** [comment]
当然有的，你再确认一下，前几天就提交的

**Comment by dayongchan** [comment]
嗯，在mvnrepository.com上能找到，但是下载不下来。。。还是换回2.0.0先用着

**Comment by binarywang** [comment]
那你换个镜像库试试吧，推荐使用阿里云的
