### ISSUE TITLE
com.thoughtworks.xstream.io.StreamException:  : input contained no data

### ISSUE THREAD

**Issue by blankzust** [Wechat-Group/weixin-java-tools-springmvc#10]
同一支付接口调用的时候报这个错，查了一下，发现有问题在于返回的内容为空字符

**Comment by blankzust** [comment]
String responseContent = this.executeRequest(url, xmlParam);
log.debug("微信统一下单接口，URL:{},结果：{}", url, responseContent);

这里打印的结果为
`微信统一下单接口，URL:https://api.mch.weixin.qq.com/pay/unifiedorder,结果：`

**Comment by eason-zhang1** [comment]
I meet this issue again, what's wrong? thanks.
