### ISSUE TITLE
web.xml文件的schema有问题

### ISSUE THREAD

**Issue by w17731138318** [Wechat-Group/weixin-java-tools-springmvc#11]
web.xml文件的schema有问题
Java EE 7 XML schema，命名空间是 http://xmlns.jcp.org/xml/ns/javaee/
Java EE 6 XML schema，命名空间是 http://Java.sun.com/xml/ns/javaee

**Comment by FirenzesEagle** [comment]
该项目为Java EE 7 XML schema，用的命名空间就是http://xmlns.jcp.org/xml/ns/javaee啊
