### ISSUE TITLE
项目部署后会抛NPE,wechatCore里的outMessage没有考虑为null的情况

### ISSUE THREAD

**Issue by JavaKuzz** [Wechat-Group/weixin-java-tools-springmvc#14]
如果点击view菜单，比如设置成百度的url，点击后，outMessage=null，抛出空指针异常。

**Comment by binarywang** [comment]
抛空指针你需要自己处理下

**Comment by JavaKuzz** [comment]
@binarywang 这不是属于代码缺陷？

**Comment by binarywang** [comment]
好吧，才知道你说的是什么问题，因为这个demo不是我写的，没注意，它这个确实没考虑到这个问题，看其他demo就特意处理过的。

**Comment by binarywang** [comment]
以后发现问题，可以直接提交PR，便于高效解决问题

**Comment by binarywang** [comment]
优化代码已提交

**Comment by JavaKuzz** [comment]
@binarywang 谢谢你的鼓励，只是我才刚出来工作，没太多经验，还停留在怀疑状态，没那个勇气。。。
