### ISSUE TITLE
关于注解问题

### ISSUE THREAD

**Issue by senola** [wechat-group/weixin-java-tools-springmvc#2]
请教一下，为什么你这里可以直接用@Autowired 没看到配置文件里添加了 bean 
![image](https://cloud.githubusercontent.com/assets/6022948/19271864/00f5c3d4-8ff9-11e6-85cb-26d753340588.png)

**Comment by FirenzesEagle** [comment]
在MainConfig里有@Bean的注解，请注意是用Java代码的方式注解的Bean

**Comment by senola** [comment]
原来如此，非常感谢！！！
